# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9090/auth/oauth/token
      userAuthorizationUri: http://localhost:9090/auth/oauth/authorize
      clientId: myauthserver
      clientSecret: verysecretpassword
    resource:
      userInfoUri: http://localhost:9090/auth/user

time:
  url: http://localhost:8081/time

# Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:8081/*
# and automatically includes our OAuth2 token in the request headers
zuul:
  routes:
    internalApi:
      path: /api/**
      url: http://localhost:8081
    externalApi:
      path: /external/**
      url: http://some.external.webservice/

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      internalApi: oauth2
      externalApi: none