#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
#google:
#  client:
#    clientId: 233668646673605
#    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

google:
    client:
        clientId:  479670005937-ushtbr9lfp7cjtdtj9aak7bfj6unscn5.apps.googleusercontent.com
        clientSecret: XZ9p8HE-688myW-ihb6DsC67
        accessTokenUri: https://www.googleapis.com/oauth2/v3/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        scope: profile
        redirectUri: http://localhost:8080
    resource:
        userInfoUri: https://www.googleapis.com/userinfo/v2/me
        preferTokenInfo: false

github:
  client:
    clientId: cdf89792854ec0dd6579
    clientSecret: 988bee4d6f48524cfc7e85afcc6c00f22df0c593
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

user:
  url: http://localhost:8080/user

logging:
  level:
    org.springframework.security: INFO
