server:
  port: 8765

info:
  component: Zuul Server

#spring:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:9090/uaa/user

# Configure the public key to use for verifying the incoming JWT tokens
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjj4JDMgT4OoaXisEd8Nz
          uiLwum9mh8BH1l9Atpe+uZkepf3Vnv0Bhxn0BGR+kYGwEHZPVpWsHEyTfIRdinaQ
          vlPaxWJquQW25yYstrCuQTKJvFjSO/cX/V4OGi1RUj76mOpwzkm1Kui3R7Sfh8Zo
          WO0GiWIFJqNBsZ9b1wOfBMXnge+A+u/qxVNnTFpwCVj6k2Yb4YUsmLNCmND7E3Ra
          BnrNQWqMU2numhV+ADpmVH08m/+pWdZ896uYu/tvQnz3agvZPcFsEst7LcNAWQFT
          eNLkfwVfepKWa9jPELemtTLf1MkMppU+Lj1UNCr8x4Y6EupRDZhplVNtqYsPNDpO
          7wIDAQAB
          -----END PUBLIC KEY-----

# External OAuth2 provider configuration - Google
google:
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#zuul:
#  ignoredServices: "*"
#  prefix: /api
#  routes:
#    productapi:
#      path: /product/**
#      sensitiveHeaders:
#      url: http://localhost:8071

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

# Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:8081/*
# and automatically includes our OAuth2 token in the request headers
#TODO this can be organized better
zuul:
  routes:
    internalApi:
      path: /api/**
      sensitiveHeaders:
      url: http://localhost:8081
    externalApi:
      path: /external/**
      url: http://some.external.webservice/

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      internalApi: oauth2
      externalApi: none