# Make the application available at http://localhost:9090/auth
server:
  port: 9090
  contextPath: /auth

# Our certificate settings for enabling JWT tokens
jwt:
  certificate:
    store:
      file: classpath:/certificate/my-auth-server.jks
      password: storepassword
    key:
      alias: myauthserver
      password: keypassword